### ISSUE TITLE
Undefined class constant 'RFC3339'

### ISSUE THREAD

**Issue by netunlimited** [Ne-Lexa/google-play-scraper#10]
Hi there,

I'm running PHP 7.1.33, calling getAppInfo fails with this error:

Uncaught Error: Undefined class constant 'RFC3339' in /data/www/cms/vendor/nelexa/google-play-scraper/src/Model/AppInfo.php:560 Stack trace: #0 /data/www/cms/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php(41): Nelexa\GPlay\Model\AppInfo->asArray() 

Please advice.

**Comment by Ne-Lexa** [comment]
Fixed in 0.2.1 version.

**Comment by netunlimited** [comment]
Thanks for fixing so fast!!
