### ISSUE TITLE
"Unable to read from stream" error in production

### ISSUE THREAD

**Issue by noumanhabib** [Ne-Lexa/google-play-scraper#11]
I have a error when using google-play-scrapper in production. It work fine at localhost but not work in production.
Below is screenshort of error.
![screencapture-digiplanet-org-admin-app-refresh-1-simple-2021-04-22-14_08_06](https://user-images.githubusercontent.com/77984959/115688048-370c0300-a374-11eb-84fd-67748d03b752.png)

Stream object before causing error screenshort is also below.
![stream pic](https://user-images.githubusercontent.com/77984959/115688216-615dc080-a374-11eb-93c2-63fbc0b577ff.png)

I am using it in
Laravel 8
Guzzlehttp: 6.5
PHP: 7.4 (at production)

Also each request fail after 20s and show read stream error as up.
Is there any connection timeout set for 20s?

**Comment by Ne-Lexa** [comment]
Try installing `ext-curl` if it is not installed.  
There are methods to increase the timeout. 

```php
$gplay
    ->setConnectTimeout(60)
    ->setTimeout(60);
```

**Comment by noumanhabib** [comment]
Yes it is connection timeout error. You can set a higher value then it work.
