### ISSUE TITLE
getAppVersion returns NULL sometimes

### ISSUE THREAD

**Issue by 89z** [Ne-Lexa/google-play-scraper#12]
Using this program:

~~~php
<?php
require 'autoload.php';

$gplay = new \Nelexa\GPlay\GPlayApps(
   $defaultLocale = 'en_US', $defaultCountry = 'us'
);

$appInfo = $gplay->getAppInfo('com.mojang.minecraftpe');
var_dump($appInfo->getAppVersion());

$appInfo = $gplay->getAppInfo('com.google.android.youtube');
var_dump($appInfo->getAppVersion());
~~~

I get this result:

~~~
string(10) "1.17.11.01"
NULL
~~~

**Comment by Ne-Lexa** [comment]
@89z It means: Varies with device.

**Comment by 89z** [comment]
Cant I just ignore the device, and get latest version somehow?

**Comment by Ne-Lexa** [comment]
@89z No, you can't. This value is taken from the page https://play.google.com/store/apps/details/YouTube?id=com.google.android.youtube&hl=en&gl=US

**Comment by 89z** [comment]
sorry, I didnt mean that to be a question. What I want **is possible**, just maybe not with this package. That page youve linked, is not the only source of version information. I will need to keep looking I guess.

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/googleplay
