### ISSUE TITLE
ERROR: InvalidArgumentException: Developer id cannot be null or empty

### ISSUE THREAD

**Issue by kobyle69** [Ne-Lexa/google-play-scraper#15]
```
$gplay = new GPlayApps();
$appInfo = $gplay->search('Apar Games', 500);
var_dump($appInfo);
```

Error:

> InvalidArgumentException: Developer id cannot be null or empty. Solution: $developerBuilder->setId(...);
> .../vendor/nelexa/google-play-scraper/src/Model/Developer.php:84

**Comment by Ne-Lexa** [comment]
@kobyle69, unfortunately I could not reproduce this error. 
If the error is still repeated, go through the debugger, find the application where the exception is raised and let me know.

**Comment by Ne-Lexa** [comment]
Hello.
The problem has not been identified or has already been solved.
