### ISSUE TITLE
Error on add lib to project

### ISSUE THREAD

**Issue by Porshe** [Ne-Lexa/google-play-scraper#16]
Error on add lib to project
```

  Problem 1
    - nelexa/http-client-simple-cache[1.0.1, ..., 1.1.1] require guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - nelexa/google-play-scraper 0.2.1 requires nelexa/http-client-simple-cache ^1.0.1 -> satisfiable by nelexa/http-client-simple-cache[1.0.1, 1.1, 1.1.1].
    - Root composer.json requires nelexa/google-play-scraper ^0.2.1 -> satisfiable by nelexa/google-play-scraper[0.2.1].

```

Please, update versions in your required "nelexa" libs.

**Comment by debadaracco** [comment]
+1

**Comment by Ne-Lexa** [comment]
You can't just go to guzzle 7 by changing just the version. The code became incompatible because of strict typing. We need to rework it, keeping the caching. Maybe switch to Symfony HTTP-Client. I will do this when I have some free time. 
PRs are welcome.

**Comment by debadaracco** [comment]
> Error on add lib to project
> 
> ```
> 
>   Problem 1
>     - nelexa/http-client-simple-cache[1.0.1, ..., 1.1.1] require guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
>     - nelexa/google-play-scraper 0.2.1 requires nelexa/http-client-simple-cache ^1.0.1 -> satisfiable by nelexa/http-client-simple-cache[1.0.1, 1.1, 1.1.1].
>     - Root composer.json requires nelexa/google-play-scraper ^0.2.1 -> satisfiable by nelexa/google-play-scraper[0.2.1].
> ```
> 
> Please, update versions in your required "nelexa" libs.

you can test the following solution

`"guzzlehttp/guzzle": "^6.5|^7.0.1",`
