### ISSUE TITLE
Error in Search Suggestions

### ISSUE THREAD

**Issue by hki98** [Ne-Lexa/google-play-scraper#18]
Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://market.android.com/suggest/SuggRequest?json=1&c=3&query=fb&hl=en_US&gl=us` resulted in a `503 Service Unavailable` response: <html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style>

**Comment by Ne-Lexa** [comment]
Thanks for the issue. Fixed.
