### ISSUE TITLE
PHP 8.1. - Fails

### ISSUE THREAD

**Issue by BrunoFischerGermany** [Ne-Lexa/google-play-scraper#19]
Hi 

i get this messages out

`Deprecated: Return type of Nelexa\GPlay\Model\Developer::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

`Deprecated: Return type of Nelexa\GPlay\Model\Category::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

`Deprecated: Return type of Nelexa\GPlay\Model\HistogramRating::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

`Deprecated: Return type of Nelexa\GPlay\Model\Review::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

`Deprecated: Return type of Nelexa\GPlay\Model\App::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

`Deprecated: Return type of Nelexa\GPlay\Model\ImageInfo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/composer/vendor/nelexa/google-play-scraper/src/Model/JsonSerializableTrait.php on line 29`

php -v said 
`PHP 8.1.3 (cli) (built: Feb 21 2022 14:48:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies`

Can You help?

Greets

**Comment by Ne-Lexa** [comment]
Hello.
This will be fixed soon with Guzzle 7 support.

**Comment by BrunoFischerGermany** [comment]
Hello. Thanks for the Information :)
