### ISSUE TITLE
Is it possible to get the all the available apps from play store?

### ISSUE THREAD

**Issue by Dibbyo456** [Ne-Lexa/google-play-scraper#2]
same as title

**Comment by Ne-Lexa** [comment]
No, you cannot get all available applications, but you can use these methods:
- [GPlayApps::search](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappssearch-docs)
- [GPlayApps::getListApps](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappsgetlistapps-docs)
- [GPlayApps::getTopApps](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappsgettopapps-docs)
- [GPlayApps::getNewApps](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappsgetnewapps-docs)
- [GPlayApps::getDeveloperApps](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappsgetdeveloperapps-docs)
- [GPlayApps::getSimilarApps](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/README.md#gplayappsgetsimilarapps-docs)
