### ISSUE TITLE
Error in 0.3.1

### ISSUE THREAD

**Issue by hki98** [Ne-Lexa/google-play-scraper#20]
Hi,
I'm getting this error after upgrading to the latest version, can you please fix it.
PHP VERSION: 8.1

`Fatal error: Uncaught Error: Undefined constant "STDOUT" in /vendor/nelexa/google-play-scraper/src/HttpClient/ConsoleLog.php:23 Stack trace: #0 /vendor/guzzlehttp/guzzle/src/Middleware.php(192): Nelexa\GPlay\HttpClient\ConsoleLog->log() #1 /vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 /vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #5 /vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #6 /vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute() #7 /vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #8 /vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #9 /vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #10 /vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #11 /vendor/nelexa/google-play-scraper/src/HttpClient/HttpClient.php(126): GuzzleHttp\Promise\Promise->wait() #12 /vendor/nelexa/google-play-scraper/src/GPlayApps.php(967): Nelexa\GPlay\HttpClient\HttpClient->request() #13 /vendor/nelexa/google-play-scraper/src/GPlayApps.php(1170): Nelexa\GPlay\GPlayApps->getClusterPages() #14 /vendor/nelexa/google-play-scraper/src/GPlayApps.php(1128): Nelexa\GPlay\GPlayApps->fetchAppsFromClusterPages() #15 /controller/HomeController.php(32): Nelexa\GPlay\GPlayApps->getTopApps() #16 /index.php(2): require('/home/...') #17 {main} thrown in /vendor/nelexa/google-play-scraper/src/HttpClient/ConsoleLog.php on line 23`

**Comment by Ne-Lexa** [comment]
@hki98, what OS do you have?

**Comment by Ne-Lexa** [comment]
Fixed. Update the version of the library to 0.3.2.
