### ISSUE TITLE
Argument 1 passed to Nelexa\GPlay\Scraper\Extractor\AppsExtractor::extractApp() must be of the type array, null given, called in

### ISSUE THREAD

**Issue by kobyle69** [Ne-Lexa/google-play-scraper#24]
`Argument 1 passed to Nelexa\GPlay\Scraper\Extractor\AppsExtractor::extractApp() must be of the type array, null given, called in /home/public_html/Application/Libs/vendor/nelexa/google-play-scraper/src/Scraper/ClusterAppsScraper.php on line 56`

Getting the above error in the past weeks, any idea?

**Comment by Ne-Lexa** [comment]
The problem is solved.
Update the version to 0.4
