### ISSUE TITLE
Unable to get data for this application

### ISSUE THREAD

**Issue by moshbo** [Ne-Lexa/google-play-scraper#28]
Hey,

I'm using this repository to pull data from google play store.
It was perfectly working, but now I'm getting this error:

Next Nelexa\GPlay\Exception\GooglePlayException: Unable to get data for this application. in /var/www/html/wp-content/plugins/get-info-google-play-app/vendor/nelexa/google-play-scraper/src/GPlayApps.php:227
Stack trace:
#0 /var/www/html/wp-content/plugins/get-info-google-play-app/vendor/nelexa/google-play-scraper/src/GPlayApps.php(191): Nelexa\GPlay\GPlayApps->getAppsInfo()
#1 /var/www/html/wp-content/plugins/get-info-google-play-app/public/class-get-info-google-play-app-public.php(78): Nelexa\GPlay\GPlayApps->getAppInfo()
#2 /var/www/html/wp-includes/class-wp-hook.php(307): Get_Info_Google_Play_App_Public->get_info_google_play_app()
#3 /var/www/html/wp-includes/plugin.php(191): WP_Hook->apply_filters()
#4 /var/www/html/wp-content/plugins/get-info-google-play-app/get-info-google-play-app.php(97): apply_filters()
#5 /var/www/html/wp-content/plugins/appdash/page-templates/cron-template.php(65): get_info_google_play_app()
#6 /var/www/html/wp-includes/template-loader.php(106): include('...')
#7 /var/www/html/wp-blog-header.php(19): require_once('...')
#8 /var/www/html/index.php(17): require('...')
#9 {main}
  thrown in /var/www/html/wp-content/plugins/get-info-google-play-app/vendor/nelexa/google-play-scraper/src/GPlayApps.php on line 227

Tnx for helpers,
M.

**Comment by Ne-Lexa** [comment]
Hello.
Check that you use the latest version of the library.
