### ISSUE TITLE
Warning:  Trying to access array offset on value of type null in /vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php on lin 75

### ISSUE THREAD

**Issue by sayedsahin** [Ne-Lexa/google-play-scraper#30]
When i submit **com.vivo.easyshare**, **com.seewo.screensharepro.client2** and **com.shareall.transfer** apps. I get some error

<br />
<b>Warning</b>:  Trying to access array offset on value of type null in <b>vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php</b> on line <b>75</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Nelexa\GPlay\Scraper\AppInfoScraper::extractHistogramRating(): Argument #1 ($data) must be of type array, null given, called in vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php on line 75 and defined in vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php:212
Stack trace

> 

#0 vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php(75): Nelexa\GPlay\Scraper\AppInfoScraper-&gt;extractHistogramRating(NULL)

#1 vendor/nelexa/google-play-scraper/src/HttpClient/HttpClient.php(164): Nelexa\GPlay\Scraper\AppInfoScraper-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array)
#2 vendor/guzzlehttp/promises/src/Promise.php(204): Nelexa\GPlay\HttpClient\HttpClient-&gt;Nelexa\GPlay\HttpClient\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#4 vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#5 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue-&gt;run()
#6 vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler-&gt;tick()
#7 vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler-&gt;execute(true)
#8 vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise-&gt;invokeWaitFn()
#9 vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise-&gt;waitIfPending()
#10 vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise-&gt;invokeWaitList()
#11 vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise-&gt;waitIfPending()
#12 vendor/guzzlehttp/promises/src/EachPromise.php(116): GuzzleHttp\Promise\Promise-&gt;wait()
#13 vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\EachPromise-&gt;GuzzleHttp\Promise\{closure}(true)
#14 vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise-&gt;invokeWaitFn()
#15 vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise-&gt;waitIfPending()
#16 vendor/nelexa/google-play-scraper/src/HttpClient/HttpClient.php(201): GuzzleHttp\Promise\Promise-&gt;wait()
#17 vendor/nelexa/google-play-scraper/src/GPlayApps.php(219): Nelexa\GPlay\HttpClient\HttpClient-&gt;requestPool(Array)
#18 vendor/nelexa/google-play-scraper/src/GPlayApps.php(184): Nelexa\GPlay\GPlayApps-&gt;getAppsInfo(Array)
#19 app/Controllers/GplayController.php(21): Nelexa\GPlay\GPlayApps-&gt;getAppInfo('com.vivo.easysh...')
#20 app/Systems/Route.php(38): Controllers\GplayController-&gt;index('com.vivo.easysh...')
#21 public/index.php(6): include_once('/home/playstore...')
#22 {main}

Next Nelexa\GPlay\Exception\GooglePlayException: Nelexa\GPlay\Scraper\AppInfoScraper::extractHistogramRating(): Argument #1 ($data) must be of type array, null given, called in vendor/nelexa/google-play-scraper/src/Scraper/AppInfoScraper.php on line 75 in vendor/nelexa/google-play-scraper/src/GPlayApps.php:221
Stack trace:
#0 vendor/nelexa/google-play-scraper/src/GPlayApps.php(184): Nelexa\GPlay\GPlayApps-&gt;getAppsInfo(Array)
#1 app/Controllers/GplayController.php(21): Nelexa\GPlay\GPlayApps-&gt;getAppInfo('com.vivo.easysh...')
#2 app/Systems/Route.php(38): Controllers\GplayController-&gt;index('com.vivo.easysh...')
#3 public/index.php(6): include_once('/home/playstore...')
#4 {main}
  thrown in <b>vendor/nelexa/google-play-scraper/src/GPlayApps.php</b> on line <b>221</b><br />

**Comment by sayedsahin** [comment]
And these apps also return errors:

com.cebook
com.shashank.sony.cprogrammingbyshashank
interview.programming.coding.c
com.outsideandroider.cplacementquestions
com.newandromo.dev17714.app1081381
cprograming.exampleebook2018
com.turbocgraphics
com.pshady.cprograms
com.edugorilla.citclang
fcsa.esy.es.programaremc
com.searchmywebsiteservices.LEARN_C
com.aniketjain.cprograms
com.cprogramming.examples
vitrix.chase.howtolearn.ctutorial.patternprogram.cinterview.cmcq.learncprogramming
com.yusuf.cprogram
ezegut.technologies.j7.s7.ctheme.theme.launcher
pemrogramandasarsatu.marisinau.com.pemrogramandasarsatu
tech.central.ctocoin
com.qcm.cpp
wali.c4droid
com.crackitinterview.cinterviewqa
com.CL.dev20.app20
mit2.mit2canalp
com.learnity.learn_c_programming
com.saurabhkamal.programminginc
com.c.interview.viva.questions
com.rohitsrivastva.cintheloop
in.collectiva.cka
com.q_a.learncprogrammingwithbestpracticecode
com.icaw.shk.cprogramming.learn.clanguage
c.rammingamepro
com.dexterousdevelopers.cprogrammingtutorials
com.japangor.cprograms
c.programs2
sh.eagletech.cpp
com.balajitech.c
com.programmarc.cprogrammingbangla
com.sitseducators.patchupwithc
com.siddhi.CLearningApp
com.cprogramming.bca
com.sitseducators.patchupwithcpro
com.C_Examples.C_Programming
com.algosoftware.learnc
com.ayhan.creference
com.biiteducation.c
com.me.code_world
com.bee.clanguage.Tutorial
com.c.creative.cprogramming
com.cprogramming.mcqallcprograms.computerbitspradip
com.newageproductions.learnc
com.clanguage.pradip.bitsofcomputer
in.softecks.c
com.somil.cprogrammingnotes
com.vszone.cprogramsAdv
com.vivek.cnotes
kr.co.SoftHeaven.Free_CProgrammingStudyStep2
com.coolbase.cprogramming
com.roboisoft.cprogrammingapp
com.hbss.cprogrammingapp.cprogramming
com.hbss.cprogrammingapp.cprogramming
com.learningApp.programming.CLanguage
com.neckster.c_tester
com.finaldesk.cprogramming
com.roboisoft.basicprogrammingsolution
com.programmingpulsetechnology.thiru.cprogramming
com.clanguage.cprogramming
earthcoding.c.learn.learnc
club.onepercent.c_compiler
com.coding.dmr.c
com.raoappstudios.learncprogramming
com.alphazstudio.learncprogramming
com.noobdev7.cprogrammingapp
com.coding.cprogramming
com.C_Language.learn_offline
com.codetoinvent.malik.cprogramming
c.learnc.learn.cx.coding.programming.c.tutorials.codingx

**Comment by Ne-Lexa** [comment]
What version do you use?
Update the version to the last.

**Comment by sayedsahin** [comment]
> What version do you use?
> Update the version to the last.

I used latest version (0.4.0)
