### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by pixelgroup-israel** [Ne-Lexa/google-play-scraper#31]
Hi,
As of this morning I'm getting notices when using this library:

Notice: Uninitialized string offset: 2 in /var/www/html/public_html/vendor/nelexa/google-play-scraper/src/Scraper/Extractor/ReviewsExtractor.php on line 55

Notice: Uninitialized string offset: 3 in /var/www/html/public_html/vendor/nelexa/google-play-scraper/src/Scraper/Extractor/ReviewsExtractor.php on line 55

The end result is that I'm not getting the data from Google Play.

Doe's anyone knows what this means?

Thanks,
Amit

**Comment by kobyle69** [comment]
+1

Getting same error from yesterday

**Comment by Ne-Lexa** [comment]
Fixed in version 0.4.0.4
