### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by masoomdil** [Ne-Lexa/google-play-scraper#32]
Hello 
scraper is not working any more its giving me HTTP ERROR 500,I am using on https://pakibuz.com/apkn/fetch.php
that was working but stopped now please guide me how I can fix it

**Comment by sayedsahin** [comment]
**I get this error**

Warning: Trying to access array offset on value of type null in \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php on line 55

Warning: Trying to access array offset on value of type null in \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php on line 55

Fatal error: Uncaught TypeError: Nelexa\GPlay\Model\GoogleImage::__construct(): Argument #1 ($url) must be of type string, null given, called in \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php on line 55 and defined in \vendor\nelexa\google-play-scraper\src\Model\GoogleImage.php:169 Stack trace: #0 \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php(55): Nelexa\GPlay\Model\GoogleImage->__construct(NULL) #1 \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php(38): Nelexa\GPlay\Scraper\Extractor\ReviewsExtractor::extractReview(Object(Nelexa\GPlay\Model\AppId), Array) #2 \vendor\nelexa\google-play-scraper\src\Scraper\AppInfoScraper.php(334): Nelexa\GPlay\Scraper\Extractor\ReviewsExtractor::extractReviews(Object(Nelexa\GPlay\Model\AppId), Array) #3 \vendor\nelexa\google-play-scraper\src\Scraper\AppInfoScraper.php(110): Nelexa\GPlay\Scraper\AppInfoScraper->extractReviews(Object(Nelexa\GPlay\Model\AppId), Array) #4 \vendor\nelexa\google-play-scraper\src\HttpClient\HttpClient.php(166): Nelexa\GPlay\Scraper\AppInfoScraper->__invoke(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array) #5 \vendor\guzzlehttp\promises\src\Promise.php(204): Nelexa\GPlay\HttpClient\HttpClient->Nelexa\GPlay\HttpClient\{closure}(Object(GuzzleHttp\Psr7\Response)) #6 \vendor\guzzlehttp\promises\src\Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #7 \vendor\guzzlehttp\promises\src\TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #8 \vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #9 \vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #10 \vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #11 \vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #12 \vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #13 \vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #14 \vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #15 \vendor\guzzlehttp\promises\src\EachPromise.php(116): GuzzleHttp\Promise\Promise->wait() #16 \vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Promise\EachPromise->GuzzleHttp\Promise\{closure}(true) #17 \vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #18 \vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #19 \vendor\nelexa\google-play-scraper\src\HttpClient\HttpClient.php(203): GuzzleHttp\Promise\Promise->wait() #20 \vendor\nelexa\google-play-scraper\src\GPlayApps.php(219): Nelexa\GPlay\HttpClient\HttpClient->requestPool(Array) #21 \vendor\nelexa\google-play-scraper\src\GPlayApps.php(184): Nelexa\GPlay\GPlayApps->getAppsInfo(Array) #22 \app\Controllers\GplayController.php(21): Nelexa\GPlay\GPlayApps->getAppInfo('women.workout.f...') #23 \app\Systems\Route.php(38): Controllers\GplayController->index('women.workout.f...') #24 \public\index.php(6): include_once('D:\\development\\...') #25 {main} Next Nelexa\GPlay\Exception\GooglePlayException: Nelexa\GPlay\Model\GoogleImage::__construct(): Argument #1 ($url) must be of type string, null given, called in \vendor\nelexa\google-play-scraper\src\Scraper\Extractor\ReviewsExtractor.php on line 55 in \vendor\nelexa\google-play-scraper\src\GPlayApps.php:221 Stack trace: #0 \vendor\nelexa\google-play-scraper\src\GPlayApps.php(184): Nelexa\GPlay\GPlayApps->getAppsInfo(Array) #1 \app\Controllers\GplayController.php(21): Nelexa\GPlay\GPlayApps->getAppInfo('women.workout.f...') #2 \app\Systems\Route.php(38): Controllers\GplayController->index('women.workout.f...') #3 \public\index.php(6): include_once('D:\\development\\...') #4 {main} thrown in \vendor\nelexa\google-play-scraper\src\GPlayApps.php on line 221

**Comment by mhnazmul** [comment]
Also not working
