### ISSUE TITLE
Hello.its not working again

### ISSUE THREAD

**Issue by masoomdil** [Ne-Lexa/google-play-scraper#33]
Hello.
Check that you use the latest version of the library.

_Originally posted by @Ne-Lexa in https://github.com/Ne-Lexa/google-play-scraper/issues/28#issuecomment-1165488911_

**Comment by masoomdil** [comment]
yes i used new library but i am still getting 500 error

**Comment by Ne-Lexa** [comment]
Duplicate of #32
