### ISSUE TITLE
Can't get permissions

### ISSUE THREAD

**Issue by gagandeep995** [Ne-Lexa/google-play-scraper#6]
Please help me to get the permissions used by an app.

**Comment by Ne-Lexa** [comment]
See method [GPlayApps::getPermissions()](https://github.com/Ne-Lexa/google-play-scraper/blob/master/docs/classes/GPlayApps/gplayapps.getpermissions.md)

```php
$appId = 'com.facebook.katana';

$gplay = new GPlayApps();
$permissions = $gplay->getPermissions($appId);
```
