### ISSUE TITLE
Info returned by $gplay->getAppInfo($appId)  has 'released' => NULL   property

### ISSUE THREAD

**Issue by GrinOleksandr** [Ne-Lexa/google-play-scraper#8]
example:
`$gplay->getAppInfo("com.Hawi.SkyDream");`

what are the possible reasons for that?
does app can have not release date?

**Comment by GrinOleksandr** [comment]
ahha, I've got it.
Looks like results of that response also is related to country

**Comment by Ne-Lexa** [comment]
For which country and locale does it return null?

```php
$appInfos = $gplay->getAppInfoForAvailableLocales('com.Hawi.SkyDream');
foreach ($appInfos as $locale => $appInfo) {
    echo $locale . ' => ' . $appInfo->getReleased()->format('Y-m-d') . PHP_EOL;
}
// vi => 2020-06-22
// hy_AM => 2020-06-22
// ko_KR => 2020-06-22
```

**Comment by GrinOleksandr** [comment]
that results was for country "ua" and locale "en_US" , but now it  is not null

**Comment by GrinOleksandr** [comment]
I came back to work and found more examples, this is only few of them
I used the code provided by you in this issue

$appInfos = $gplay->getAppInfoForAvailableLocales('com.nexon.v4gb');
foreach ($appInfos as $locale => $appInfo) {
    echo $locale . ' => ' . $appInfo->getReleased() . PHP_EOL;
}

// en_US => 
// de_DE => 
// fr_FR => 
// hy_AM => 
// ko_KR => 
// ru_RU => 
// th => 
// zh_CN => 

the same results for:
com.blizzard.diablo.immortal
com.byaliens.bid.wars.stars.multiplayer.auction.battles
com.mojang.minecrafttrialpe

and a lot more 
However I see that this is a temporary issue, maybe it is related to google play services

**Comment by Ne-Lexa** [comment]
Release data not provided, which means the release date is null.
