### ISSUE TITLE
Locale and country is missing from initial cluster page url

### ISSUE THREAD

**Issue by Victor-emil** [Ne-Lexa/google-play-scraper#9]
When I initialize the GPlayApps class like this `$this->googlePlay = new GPlayApps('da_DK', 'dk');` and access the top apps like this `$this->googlePlay->getTopApps()` I get the correct results locally, but when doing it on the server I retrieve a bunch of german results (The server is located in Frankfurt). I tried locally with a VPN pointing to Frankfurt and I am now also retrieving a bunch of german results although I initialize the class with a locale and a country. 

I tried to debug the library and I noticed that the locale and country are not present in the initial request starting on line 853 in the GPlayApps class. This means that the first 50 results are from Germany and the remaining results are from Denmark.

For testing I just hardcoded the country and now it gives me the correct results even though the VPN is pointing the Frankfurt. 
![image](https://user-images.githubusercontent.com/8555068/91729232-8793dd80-eba4-11ea-9777-851d9394cd73.png)

**Comment by Ne-Lexa** [comment]
Thanks for the issue.
The problem has been fixed.
Update dependencies.

**Comment by Victor-emil** [comment]
@Ne-Lexa. Fantastic! It's working. Thank you.
